### PR TITLE
chore!: update plugin to capacitor 5

### PR DESCRIPTION
**Pull request by holmio**

### CODE REVIEW

**Review by fmendoza — APPROVED** [review]

**Comment by akdasa** [comment]
Thanks guys for keeping this pack up to date! Can't wait for it to merge :)

**Comment by sync667** [comment]
Anyone merge that :) @epicshaggy @mlynch @lcsoka ?

**Comment by yllaw** [comment]
@rdlabo, sorry to bother but is it possible to merge this pull request?

**Comment by sync667** [comment]
Temporary if someone have to use this and need dist because of builds etc. Use my fork like this: `"@capacitor-community/apple-sign-in": "github:sync667/apple-sign-in#update-to-capacitor-5",`

**Comment by akdasa** [comment]
🎉🥳🎊

**Comment by junaid5546** [comment]
Hi guys I have added that plugin but in android it was causing issue, it throws error while i am trying to create android build it says 


Caused by: java.lang.RuntimeException: Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}

**Comment by piotr-cz** [comment]
@junaid5546 
Are you sure that you have tried this plugin after it has been updated to capacitor 5?

The [issue are are referring to](https://capacitorjs.com/docs/updating/plugins/5-0#move-package-to-buildgradle) has been addressed in this pull request here:

https://github.com/capacitor-community/apple-sign-in/commit/1a7f3452b8982aa77cd6137bd363e270f04f263c#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR20

**Pull request merged**
